// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: Input.proto

package avatar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deviceid  string `protobuf:"bytes,1,opt,name=deviceid,proto3" json:"deviceid,omitempty"`
	Movieid   string `protobuf:"bytes,2,opt,name=movieid,proto3" json:"movieid,omitempty"`
	Category  string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Ptf       int64  `protobuf:"varint,4,opt,name=ptf,proto3" json:"ptf,omitempty"`
	Key       string `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	PageIndex int64  `protobuf:"varint,6,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	PageSize  int64  `protobuf:"varint,7,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *Input) Reset() {
	*x = Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Input_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_Input_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_Input_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetDeviceid() string {
	if x != nil {
		return x.Deviceid
	}
	return ""
}

func (x *Input) GetMovieid() string {
	if x != nil {
		return x.Movieid
	}
	return ""
}

func (x *Input) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Input) GetPtf() int64 {
	if x != nil {
		return x.Ptf
	}
	return 0
}

func (x *Input) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Input) GetPageIndex() int64 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *Input) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_Input_proto protoreflect.FileDescriptor

var file_Input_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0xb7, 0x01, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x6f, 0x76, 0x69, 0x65, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x74, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x70, 0x74, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Input_proto_rawDescOnce sync.Once
	file_Input_proto_rawDescData = file_Input_proto_rawDesc
)

func file_Input_proto_rawDescGZIP() []byte {
	file_Input_proto_rawDescOnce.Do(func() {
		file_Input_proto_rawDescData = protoimpl.X.CompressGZIP(file_Input_proto_rawDescData)
	})
	return file_Input_proto_rawDescData
}

var file_Input_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Input_proto_goTypes = []interface{}{
	(*Input)(nil), // 0: avatar.Input
}
var file_Input_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Input_proto_init() }
func file_Input_proto_init() {
	if File_Input_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Input_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Input_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Input_proto_goTypes,
		DependencyIndexes: file_Input_proto_depIdxs,
		MessageInfos:      file_Input_proto_msgTypes,
	}.Build()
	File_Input_proto = out.File
	file_Input_proto_rawDesc = nil
	file_Input_proto_goTypes = nil
	file_Input_proto_depIdxs = nil
}
